### PR TITLE
Recompiling maos binaries

### PR DESCRIPTION
**Pull request by vigji**
I recompiled the binaries after tracking down exactly where the source code was coming from (unsure about version of last commit)

### CODE REVIEW

**Comment by adamltyson** [comment]
So these are the versions that should be included going forward?

Could you fix the conflicts, and also include the source files, and the commands used to generate them?

**Comment by vigji** [comment]
Do you want to keep the source here even though it's in another git repo?

**Comment by adamltyson** [comment]
Yeah, just for now, so we have the versions used for each OS. Once we have the same version compiled for each OS, we can just have just the one (in case anyone needs to recompile it).

**Comment by vigji** [comment]
Where do you want me to put the commands for the compilation? A new docs page?

**Comment by adamltyson** [comment]
I’m going to have an overhaul of all the docs, so something like a `compliation.txt` file in binaries directory is fine.

**Comment by vigji** [comment]
I added the files. I can't solve the conflicts, I don't have write access - just keep the files from this branch, they are for sure compiled from the pushed source files

**Comment by adamltyson** [comment]
Fixed merge conflicts, zipped the source file and moved it.

If it make sense to you, I think the plan should be:
* Compile binaries for windows and linux with this version of niftyreg
* Test that they function the same
    * If so, update the test data
    * If not, make test assert statements approx (assuming the differences are small)
* Move binaries into `neuro`

**Comment by vigji** [comment]
Makes perfect sense! Although to me it would make sense to keep them in `amap-python`, that's ultimately yours and your lab software infrastructure so that's for your to judge! :)

**Pull request merged**
